Help and validation added.

diff --git a/bin_scripts/cdown b/bin_scripts/cdown
--- a/bin_scripts/cdown
+++ b/bin_scripts/cdown
@@ -3,16 +3,57 @@
 command -v lolcat >/dev/null 2>&1 || { echo >&2 "I require lolcat but it's not installed.  Aborting."; exit 1; }
 command -v figlet >/dev/null 2>&1 || { echo >&2 "I require figlet but it's not installed.  Aborting."; exit 1; }
 
-if [[ $# -ne 1 ]]; then
-    echo "Illegal number of parameters. This scipt expects 1 parameter (a number)"
+Help()
+{
+	echo "Count down from certain number of seconds and then beep."
+	echo
+	echo "Syntax: $(basename $0) [-h] seconds [beep]"
+	echo 
+	echo "options:"
+	echo "h       Print this Help."
+	echo "seconds Count down this many seconds."
+	echo "beep    Beep length in seconds."
+	echo
+}
+
+
+if [[ $# -lt 1 || $# -gt 2 ]] ; then
+    echo "ERROR: Illegal number of parameters."
+    echo 
+    Help
     exit 1
 fi
 
-N=$1; 
-while [[ $((--N)) > 0 ]]; do 
-        echo "$N" | figlet -c | lolcat && sleep 1; 
+if [ "$1" == "-h" ]; then
+	Help
+	exit 0
+fi
+
+ARG1=$1;     # Number of seconds to count down.
+ARG2=${2:-1} # Beep length in seconds.
+
+re='^[0-9]+$'
+if ! [[ $ARG1 =~ $re ]] ; then
+	echo "ERROR: Not a number" >&2
+	echo
+	Help
+	exit 1
+fi
+
+if [[ $# -gt 1 ]] ; then
+	if ! [[ $ARG2 =~ $re ]] ; then
+		echo "ERROR: Not a number" >&2
+		echo
+		Help
+		exit 1
+	fi
+fi
+
+while [[ $((--ARG1)) > 0 ]]; do 
+        echo "$ARG1" | figlet -c | lolcat && sleep 1; 
 done
 
-timeout 3 speaker-test -t sine -f 500 > /dev/null
+timeout -s SIGKILL ${ARG2} speaker-test -t sine -f 500 > /dev/null
 
 exit 0
+
